server.port=8065
server.servlet.session.timeout=24h

spring.datasource.driverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3308/scaddie?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
spring.datasource.username = root
spring.datasource.password = koreait

spring.security.user.password=[????]

log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
log4jdbc.dump.sql.maxlinelength=0

spring.servlet.multipart.max-file-size=2000MB
spring.servlet.multipart.max-request-size=2000MB

mybatis.type-aliases-package=com.project.scaddie.domain/*
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:/mappers/*.xml

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.thymeleaf.check-template=false
spring.thymeleaf.check-template-location=false

spring.servlet.multipart.maxFileSize=1000MB
spring.servlet.multipart.maxRequestSize=1000MB

spring.main.allow-circular-references:true

spring.mvc.pathmatch.matching-strategy:ant-path-matcher


